<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AGONEAIHub.Core\AGONEAIHub.Core.csproj" />
    <ProjectReference Include="..\AGONEAIHub.Application\AGONEAIHub.Application.csproj" />
    <ProjectReference Include="..\AGONEAIHub.Infrastructure\AGONEAIHub.Infrastructure.csproj" />
  </ItemGroup>
</Project>
